workflows:
    conversation_flow:
        steps:
            active:
                order: 10
                allowed_transitions:
                    - close
            closed:
                order: 30
                allowed_transitions:
                    - reopen
