workflows:
    conversation_flow:
        transitions:
            close:
                step_to: closed
                frontend_options:
                    icon: 'fa-check'
                transition_definition: close_definition
            reopen:
                step_to: active
                frontend_options:
                    icon: 'fa-pencil-square-o'
                transition_definition: reopen_definition
