workflows:
    conversation_flow:
        transition_definitions:
            __start___definition:
                actions:
                    - '@request_enum_entity': # set status "Active" to conversation
                        enum_code: conversation_status
                        identifier: active
                        attribute: $conversation.status
            close_definition:
                actions:
                    - '@request_enum_entity': # set status "Closed" to conversation
                        enum_code: conversation_status
                        identifier: closed
                        attribute: $conversation.status
            reopen_definition:
                actions:
                    - '@request_enum_entity': # set status "Active" to conversation
                        enum_code: conversation_status
                        identifier: active
                        attribute: $conversation.status
