datagrids:
    conversations-grid:
        extended_entity_name: 'Oro\Bundle\ConversationBundle\Entity\Conversation'
        views_list: '@oro_conversation.datagrid.conversation_view_list'
        acl_resource: oro_conversation_view
        options:
            entity_pagination: true
        source:
            type: orm
            query:
                select:
                    - partial conversation.{ id }
                    - conversation.id
                    - conversation.name
                    - conversation.messagesNumber
                    - lm.createdAt as lastMessageDate
                    - partial lm.{ id, participant } as lastm
                    - conversation.createdAt
                    - conversation.sourceEntityId
                    - conversation.sourceEntityClass
                    - CONCAT_WS(' ', own.firstName, own.lastName) as ownerName
                    - own.id as owner
                    - CONCAT(customerUser.firstName, ' ', customerUser.lastName) as customerUserName
                    - customer.name as customerName
                from:
                    - { table: 'Oro\Bundle\ConversationBundle\Entity\Conversation', alias: conversation }
                join:
                    left:
                        - { join: conversation.lastMessage, alias: lm }
                        - { join: lm.participant, alias: part }
                        - { join: conversation.owner, alias: own }
                        - { join: conversation.customer, alias: customer }
                        - { join: conversation.customerUser, alias: customerUser }
        inline_editing:
                    enable: true
        columns:
            name:
                label: oro.conversation.name.label
            messagesNumber:
                label: oro.conversation.messages.label
                inline_editing:
                    enable: false
            source:
                label: oro.conversation.source.label
                type: twig
                frontend_type: html
                template: '@OroConversation/Conversation/Datagrid/source.html.twig'
            ownerName:
                label: oro.conversation.owner.label
                inline_editing:
                    enable: true
                    editor:
                        view: oroform/js/app/views/editor/related-id-relation-editor-view
                        view_options:
                            value_field_name: owner
                    autocomplete_api_accessor:
                        class: orouser/js/tools/acl-users-search-api-accessor
                        permission_check_entity_name: Oro_Bundle_ConversationBundle_Entity_Conversation
            customerName:
                label: oro.conversation.customer.label
            customerUserName:
                label: oro.conversation.customer_user.label
            status:
                label:         oro.conversation.status.label
                frontend_type: select
                choices: "@oro_entity_extend.enum_options_provider->getEnumChoicesByCode('conversation_status')"
                translatable_options: false
            createdAt:
                label:         oro.ui.created_at
                frontend_type: datetime
            message:
                label: oro.conversation.last_message.label
                type: twig
                frontend_type: html
                template: '@OroConversation/Conversation/Datagrid/message.html.twig'
        sorters:
            columns:
                name:
                    data_name: conversation.name
                status:
                    data_name: status
                messagesNumber:
                    data_name: conversation.messagesNumber
                ownerName:
                    data_name: ownerName
                customerName:
                    data_name: customerName
                customerUserName:
                    data_name: customerUserName
                createdAt:
                    data_name: conversation.createdAt
                message:
                    data_name: lastMessageDate
            default:
                message: DESC
        filters:
            columns:
                name:
                    type:      string
                    data_name: conversation.name
                status:
                    type:      enum
                    data_name: status
                    enum_code: conversation_status
                messagesNumber:
                    type:      number
                    data_name: conversation.messagesNumber
                owner:
                    type: choice-tree
                    label: oro.conversation.owner.label
                    data_name: conversation.owner
                    autocomplete_alias: assigned_to_organization_users
                    renderedPropertyName: 'fullName'
                    className: 'Oro\Bundle\UserBundle\Entity\User'
                customerName:
                    type:      string
                    data_name: customerName
                customerUserName:
                    type:      string
                    data_name: customerUserName
                createdAt:
                    type:      datetime
                    data_name: conversation.createdAt
                message:
                    type:      datetime
                    data_name: lastMessageDate
                source:
                    type: choice
                    data_name: conversation.sourceEntityClass
                    null_value: '_empty_'
                    options:
                        field_options:
                            multiple: true
                            choices: "@oro_conversation.provider.storefront_conversation_provider->getSourceChoices"
                            translatable_options: true
        properties:
            id: ~
            view_link:
                type:       url
                route:      oro_conversation_view
                params:     [ id ]
            update_link:
                type:       url
                route:      oro_conversation_update
                params:     [ id ]
        actions:
            view:
                type:          navigate
                acl_resource:  oro_conversation_view
                label:         oro.grid.action.view
                icon:          eye
                link:          view_link
                rowAction:     true
            update:
                type:          navigate
                acl_resource:  oro_conversation_update
                label:         oro.grid.action.update
                icon:          edit
                link:          update_link

    conversation-messages-grid:
        extended_entity_name: 'Oro\Bundle\ConversationBundle\Entity\ConversationMessage'
        acl_resource: oro_conversation_view
        options:
            entity_pagination: true
        source:
            type: orm
            query:
                select:
                    - cm
                    - cm.id
                    - cm.index
                    - cm.body
                    - cm.createdAt
                    - cm.updatedAt
                from:
                    - { table: 'Oro\Bundle\ConversationBundle\Entity\ConversationMessage', alias: cm }
                join:
                    left:
                        - { join: cm.participant, alias: cp }
                where:
                    and:
                        - 'cm.conversation = :conversation_id'
            bind_parameters:
                - conversation_id
        columns:
            index:
                label: oro.conversation.conversationmessage.index.label
            from:
                label: oro.conversation.conversationmessage.from_participant.label
                type: twig
                frontend_type: html
                template: '@OroConversation/ConversationMessage/Datagrid/participantName.html.twig'
            body:
                label: oro.conversation.conversationmessage.body.label
                type: twig
                frontend_type: html
                template: '@OroConversation/ConversationMessage/Datagrid/messageBody.html.twig'
            createdAt:
                label: oro.ui.created_at
                frontend_type: datetime
            updatedAt:
                label: oro.ui.updated_at
                frontend_type: datetime
        sorters:
            columns:
                index:
                    data_name: cm.index
                body:
                    data_name: cm.body
                createdAt:
                    data_name: cm.createdAt
                updatedAt:
                    data_name: cm.updatedAt
            default:
                index: DESC
        filters:
            columns:
                body:
                    type: string
                    data_name: cm.body
                createdAt:
                    type: datetime
                    data_name: cm.createdAt
                updatedAt:
                    type: datetime
                    data_name: cm.updatedAt
