oro_conversation_bundle:
    resource: "@OroConversationBundle/Controller"
    type: attribute
    prefix: /conversation

oro_customer_frontend_conversation:
    resource: "@OroConversationBundle/Controller/Frontend/ConversationController.php"
    type: attribute
    prefix: /customer/conversation
    options:
        frontend: true
