services:
    oro_conversation.api.conversation.set_name:
        class: Oro\Bundle\ConversationBundle\Api\Processor\SetConversationName
        arguments:
            - '@oro_conversation.manager.conversation'
        tags:
            - { name: oro.api.processor, action: customize_form_data, event: pre_validate, parentAction: create, class: Oro\Bundle\ConversationBundle\Entity\Conversation }

    oro_conversation.api.customer.set_customer_user:
        class: Oro\Bundle\CustomerBundle\Api\Processor\SetCustomerUser
        arguments:
            - '@oro_api.form_property_accessor'
            - '@oro_security.token_accessor'
            - 'customerUser'
        tags:
            - { name: oro.api.processor, action: customize_form_data, event: pre_validate, requestType: frontend, parentAction: create, class: Oro\Bundle\ConversationBundle\Entity\Conversation, priority: 10 }

    oro_conversation.api.customer.set_customer:
        class: Oro\Bundle\CustomerBundle\Api\Processor\SetCustomer
        arguments:
            - '@oro_api.form_property_accessor'
            - '@oro_security.token_accessor'
            - 'customer'
        tags:
            - { name: oro.api.processor, action: customize_form_data, event: pre_validate, requestType: frontend, parentAction: create, class: Oro\Bundle\ConversationBundle\Entity\Conversation, priority: 10 }

    oro_conversation.api.compute_source_data:
        class: Oro\Bundle\ConversationBundle\Api\Processor\ComputeSourceValue
        arguments:
            - '@oro_conversation.manager.conversation'
        tags:
            - { name: oro.api.processor, action: customize_loaded_data, class: Oro\Bundle\ConversationBundle\Entity\Conversation }

    oro_conversation.api.compute_plain_body_field:
        class: Oro\Bundle\ConversationBundle\Api\Processor\ComputePlainBodyValue
        tags:
            - { name: oro.api.processor, action: customize_loaded_data, class: Oro\Bundle\ConversationBundle\Entity\ConversationMessage }

    oro_conversation.api.compute_author_participant_data_content:
        class: Oro\Bundle\ConversationBundle\Api\Processor\ComputeAuthorFieldsToParticipant
        arguments:
            - '@oro_conversation.manager.conversation_participant'
        tags:
            - { name: oro.api.processor, action: customize_loaded_data, class: Oro\Bundle\ConversationBundle\Entity\ConversationParticipant }
