services:
    oro_conversation.manager.conversation:
        class: Oro\Bundle\ConversationBundle\Manager\ConversationManager
        public: true
        arguments:
            - '@oro_entity.routing_helper'
            - '@oro_entity.entity_name_resolver'
            - '@oro_conversation.helper.entity_config_helper'
            - '@oro_customer.owner.frontend_ownership_metadata_provider'
            - '@property_accessor'
            - '@doctrine'
            - '@oro_conversation.provider.storefront_conversation_provider'
            - '@oro_api.entity_alias_resolver_registry'

    oro_conversation.manager.conversation_message:
        class: Oro\Bundle\ConversationBundle\Manager\ConversationMessageManager
        public: true
        arguments:
            - '@doctrine'
            - '@oro_conversation.manager.conversation_participant'
            - '@oro_conversation.participant_info.provider'
            - '@security.authorization_checker'

    oro_conversation.manager.conversation_participant:
        class: Oro\Bundle\ConversationBundle\Manager\ConversationParticipantManager
        public: true
        arguments:
            - '@doctrine'
            - '@oro_security.token_accessor'
            - '@oro_entity_extend.association_manager'
            - '@oro_conversation.participant_info.provider'
            - '@oro_locale.formatter.date_time'
            - '@oro_conversation.websocket.processor'
            - '@oro_security.acl_helper'

    oro_conversation.entity_field.participant_extension:
        class: Oro\Bundle\ConversationBundle\EntityExtend\ConversationParticipantEntityFieldExtension
        tags:
            - { name: oro_entity_extend.entity_field_extension, priority: 30 }

    oro_conversation.migration.extension.participant:
        class: Oro\Bundle\ConversationBundle\Migration\Extension\ConversationParticipantExtension
        tags:
            - { name: oro_migration.extension, extension_name: conversation_participant }

    oro_conversation.entity_config_dumper.extension.participant:
        class: Oro\Bundle\ConversationBundle\Tools\ConversationParticipantEntityConfigDumperExtension
        parent: oro_entity_extend.entity_config_dumper.extension.association
        tags:
            - { name: oro_entity_extend.entity_config_dumper_extension }

    oro_conversation.entity_config.conversation_participant:
        class: Oro\Bundle\ConversationBundle\EntityConfig\ConversationParticipantConfiguration
        tags:
            - oro_entity_config.validation.entity_config

    oro_conversation.activity_list.provider:
        class: Oro\Bundle\ConversationBundle\Provider\ConversationActivityListProvider
        arguments:
            - "@oro_entity.doctrine_helper"
            - "@oro_activity.association_helper"
        tags:
            - { name: oro_activity_list.provider, class: Oro\Bundle\ConversationBundle\Entity\Conversation }

    oro_conversation.provider.storefront_conversation_provider:
        arguments:
            - '@router'
        class: Oro\Bundle\ConversationBundle\Provider\StorefrontConversationProvider
        public: true

    oro_conversation.form.handler.participant_autocomplete:
        class: Oro\Bundle\ConversationBundle\Autocomplete\ParticipantSearchHandler
        arguments:
            - '@translator'
            - '@oro_search.index'
            - '@oro_activity.manager'
            - '@oro_entity_config.config_manager'
            - '@oro_entity.entity_class_name_helper'
            - '@doctrine.orm.entity_manager'
            - '@oro_entity.entity_name_resolver'
            - '@event_dispatcher'
            - '@oro_conversation.manager.conversation_participant'

    oro_conversation.helper.entity_config_helper:
        class: Oro\Bundle\ConversationBundle\Helper\EntityConfigHelper
        arguments:
            - '@oro_entity_config.config_manager'
            - '@translator'

    oro_conversation.participant_info.provider:
        class: Oro\Bundle\ConversationBundle\Participant\ParticipantInfoProvider
        arguments:
            - ~ # service locator for participant info providers
            - '@oro_conversation.participant_info.common_provider'

    oro_conversation.participant_info.common_provider:
        class: Oro\Bundle\ConversationBundle\Participant\CommonParticipantInfo
        arguments:
            - '@oro_entity.entity_name_resolver'
            - '@oro_security.token_accessor'
            - '@oro_conversation.helper.entity_config_helper'

    oro_conversation.participant_info.user_provider:
        class: Oro\Bundle\ConversationBundle\Participant\UserParticipantInfo
        arguments:
            - '@oro_attachment.provider.picture_sources'
            - '@oro_entity.entity_name_resolver'
            - '@oro_security.token_accessor'
            - '@oro_conversation.helper.entity_config_helper'
        tags:
            - { name: oro_conversation.participant_info_provider, class: Oro\Bundle\UserBundle\Entity\User }

    oro_conversation.twig.conversation_extension:
        class: Oro\Bundle\ConversationBundle\Twig\ConversationExtension
        arguments:
            - '@oro_platform.twig.service_locator'
        tags:
            - { name: twig.extension }

    oro_conversation.acl.voter.manage_messages:
        class: Oro\Bundle\ConversationBundle\Acl\Voter\ManageConversationMessagesVoter
        arguments:
            - '@oro_workflow.manager'
            - '@doctrine'
        tags:
            - { name: security.voter }

    oro_conversation.listener.participant_last_message_listener:
        class: Oro\Bundle\ConversationBundle\EventListener\ParticipantLastMessageListener
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    oro_conversation.listener.conversation_save_listener:
        class: Oro\Bundle\ConversationBundle\EventListener\ConversationSaveListener
        arguments:
            - '@oro_entity.routing_helper'
            - '@oro_activity.manager'
            - '@oro_conversation.manager.conversation'
            - '@oro_conversation.manager.conversation_participant'
            - '@oro_conversation.websocket.processor'
            - '@?oro_organizationpro.helper'
        tags:
            - { name: doctrine.orm.entity_listener, entity: 'Oro\Bundle\ConversationBundle\Entity\Conversation', event: prePersist }
            - { name: doctrine.event_listener, event: onFlush }

    oro_conversation.websocket.processor:
        class: Oro\Bundle\ConversationBundle\Model\WebSocket\WebSocketSendProcessor
        arguments:
            - '@oro_sync.websocket_client'
            - '@oro_sync.client.connection_checker'

    oro_conversation.topic.event:
        class: Oro\Bundle\SyncBundle\Topic\SecuredTopic
        arguments:
            - 'oro_conversation.event'
            - '@gos_web_socket.client.manipulator'
        tags:
            - { name: gos_web_socket.topic }

    oro_conversation.listener.conversation_message_save_listener:
        class: Oro\Bundle\ConversationBundle\EventListener\ConversationMessageSaveListener
        arguments:
            - '@security.authorization_checker'
            - '@oro_ui.html_tag_helper'
            - '@oro_activity.manager'
            - '@oro_entity_extend.enum_value_provider'
            - '@oro_conversation.manager.conversation_participant'
            - '@oro_security.token_accessor'
        tags:
            - { name: doctrine.orm.entity_listener, entity: 'Oro\Bundle\ConversationBundle\Entity\ConversationMessage', event: prePersist }

    oro_conversation.listener.storefront_conversations_navigation_listener:
        class: Oro\Bundle\ConversationBundle\EventListener\StorefrontConversationsNavigationListener
        arguments:
            - '@oro_conversation.manager.conversation_participant'
            - '@request_stack'
        tags:
            - { name: kernel.event_listener, event: oro_menu.configure.commerce_quick_access, method: onNavigationConfigure }
            - { name: kernel.event_listener, event: oro_menu.configure.commerce_quick_access_refreshing_teal, method: onNavigationConfigure }

    oro_conversation.configuration.provider.operations:
        class: Oro\Bundle\ConversationBundle\Action\Configuration\ConfigurationProviderDecorator
        decorates: oro_action.configuration.provider.operations
        arguments:
            - '@.inner'
            - '@oro_conversation.provider.storefront_conversation_provider'
            - '@oro_theme.provider.theme_configuration'
            - '@oro_layout.theme_manager'

    oro_conversation.participant_exclusion_provider:
        class: Oro\Bundle\ConversationBundle\Provider\ParticipantExclusionProvider
        public: false
        arguments:
            - '@oro_entity_config.config_manager'
        tags:
            - { name: oro_entity.exclusion_provider.api }

    oro_conversation.event_listener.conversation_participant_column_listener:
        class: Oro\Bundle\ConversationBundle\EventListener\ConversationParticipantColumnListener
        arguments:
            - '@oro_security.token_accessor'
            - '@oro_entity_extend.association_manager'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.before.conversations-grid, method: onBuildBefore }

    oro_conversation.datagrid.conversation_view_list:
        class: Oro\Bundle\ConversationBundle\Datagrid\ConversationViewList
        public: true
        arguments:
            - '@translator'

    oro_conversation.data_provider.conversation_data_provider:
        class: Oro\Bundle\ConversationBundle\Layout\DataProvider\ConversationDataProvider
        arguments:
            - '@oro_conversation.manager.conversation_participant'
            - '@request_stack'
        tags:
            - { name: layout.data_provider, alias: oro_conversation_data_provider }
