services:
    oro_conversationt.tests.entity_name_resolver.data_loader:
        class: Oro\Bundle\ConversationBundle\Tests\Functional\Environment\TestEntityNameResolverDataLoader
        decorates: oro_entity.tests.entity_name_resolver.data_loader
        arguments:
            - '@.inner'
